name: ${project.artifactId}
version: ${project.version}_${git.commit.id.abbrev}
author: aurgiyalgo
main: com.aurgiyalgo.TownyElections.TownyElections
depend: [Towny]
api-version: 1.14
commands:
  townyelections:
    usage: /<command>
    aliases: telect
    permission: townyelections.use
  elections:
    usage: <command>
    permission: townyelections.elections
  party:
    usage: /<command>
    permission: townyelections.party
    aliases: [p, pty, prty]
permissions:
  townyelections.*:
    default: op
    children:
      townyelections.use: true
      townyelections.elections.*: true
      townyelections.party.*: true
  townyelections.use:
    default: true
  townyelections.elections.*:
    default: op
    children:
      townyelections.elections.vote.*: true
      townyelections.elections.convoke.*: true
      townyelections.elections.list.*: true
      townyelections.elections.stop.*: true
      townyelections.elections.unvote.*: true
  townyelections.parties.*:
    default: op
    children:
      townyelections.party.create.*: true
      townyelections.party.add.*: true
      townyelections.party.accept.*: true
      townyelections.party.invites.*: true
      townyelections.party.setleader.*: true
      townyelections.party.promote.*: true
      townyelections.party.demote.*: true
      townyelections.party.info.*: true
  townyelections.elections.vote.*:
    description: Access to vote command
    default: op
    children:
      townyelections.elections.vote.town: true
      townyelections.elections.vote.nation: true
  townyelections.elections.convoke.*:
    description: Access to vote command
    default: op
    children:
      townyelections.elections.convoke.town: true
      townyelections.elections.convoke.nation: true
  townyelections.elections.list.*:
    description: Access to vote command
    default: op
    children:
      townyelections.elections.list.town: true
      townyelections.elections.list.nation: true
  townyelections.elections.stop.*:
    description: Access to vote command
    default: op
    children:
      townyelections.elections.stop.town: true
      townyelections.elections.stop.nation: true
  townyelections.elections.unvote.*:
    description: Access to vote command
    default: op
    children:
      townyelections.elections.unvote.town: true
      townyelections.elections.unvote.nation: true
  townyelections.party.create.*:
    description: Access to vote command
    default: op
    children:
      townyelections.party.create.town: true
      townyelections.party.create.nation: true
  townyelections.party.leave.*:
    description: Access to vote command
    default: op
    children:
      townyelections.party.leave.town: true
      townyelections.party.leave.nation: true
  townyelections.party.add.*:
    description: Access to vote command
    default: op
    children:
      townyelections.party.add.town: true
      townyelections.party.add.nation: true
  townyelections.party.invites.*:
    description: Access to vote command
    default: op
    children:
      townyelections.party.invites.town: true
      townyelections.party.invites.nation: true
  townyelections.party.setleader.*:
    description: Access to vote command
    default: op
    children:
      townyelections.party.setleader.town: true
      townyelections.party.setleader.nation: true
  townyelections.party.promote.*:
    description: Access to vote command
    default: op
    children:
      townyelections.party.promote.town: true
      townyelections.party.promote.nation: true
  townyelections.party.demote.*:
    description: Access to vote command
    default: op
    children:
      townyelections.party.demote.town: true
      townyelections.party.demote.nation: true
  townyelections.party.info.*:
    description: Access to vote command
    default: op
    children:
      townyelections.party.info.town: true
      townyelections.party.info.nation: true